### PR TITLE
Update to InkScape 1.0 / 1.1dev

### PR DESCRIPTION
**Pull request by vmario89**

### CODE REVIEW

**Comment by Shriinivas** [comment]
Thank you! I guess it would be better if the same file works with both 1.0 and 0.92. I have done changes in Paste Length. Would you like to do similar changes here as well? Please let me know.

**Comment by vmario89** [comment]
Hi,

after porting more than 50 plugins to InkScape 1.0 i personally would not do that. I removed all compability upgrades because it just creates spaghetti code. Its more clean to have old release for Python 2 based code and new release für Python 3 and InkScape 1.0; otherwise you are going to duplicate a lot of generic things with if-else-if-else-if-else-try-except-whatever :-(

**Review by Shriinivas — APPROVED** [review]

**Comment by Shriinivas** [comment]
Yes, I understand. But these scripts are quite small and maintaining a spaghetti code is perhaps less effort than maintaining 2 versions (with 90% same code) of the same script. And, I guess, the repetition of if-else / try-catch blocks can be minimized (or at least made readable) by writing wrapper functions.

**Comment by vmario89** [comment]
the question is who wants to use older InkScape in the future - usually only a really small group of people. I agree that it would not be hard to do so with the code in this repo. We could do this but i don't see the real effort for future. Next updatesfrom InkScape will bring more if-else statements for additional deprecations. :-/

**Pull request merged**
